### ISSUE TITLE
Tags section is visible on non-admin users side also

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#10]
Non-admin users are not allowed to create the tags, so I think tag tabs shouldn't be visible on their end. It gives an error when we switch to this tab. 

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/db375396-f201-4e6f-8e35-4153f802b770)

**Comment by biku1998** [comment]
@Burhanuddin-Nahargarwala please re-run and close if satisfied.
