### ISSUE TITLE
Throwing the error while creating the scenario when price value is not entered

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#12]
**Steps to Reproduce:**

- Create the scenario
- Enter the details for the scenario (name, overview, industry, level, tags, tools, etc.). The value for the price field is not entered
- Expected Result: It should give the message, Please fill in this field, as shown below

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/8bf1ac97-5821-4e9a-83dd-3d119e16364d)

- Actual Result: The following error comes, leading to confusion about why the scenario is not created.

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/3ccbb5d4-74b4-409f-abe8-f5da7c5f40d3)

**Comment by biku1998** [comment]
Hey @Burhanuddin-Nahargarwala Are you sure the error occurred due to leaving the price field blank? Because it's an optional field.

**Comment by Burhanuddin-Nahargarwala** [comment]
Yes. Because when I entered the value in price field and created the project, it successfully get created.

**Comment by biku1998** [comment]
Cool. Thanks @Burhanuddin-Nahargarwala will take a look

**Comment by biku1998** [comment]
Pls re-run this test @Burhanuddin-Nahargarwala and create a new scenario without providing the price and let me know if you are facing the same issue. If yes ping on slack, will connect to see browser logs.

**Comment by Burhanuddin-Nahargarwala** [comment]
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/ccfc3a28-280b-49ca-9039-e907fbd43ca6)

I tried creating the scenario without entering the price value, and now it's not throwing the error, but the scenario is not created. Pressed the Create button multiple times.

**Comment by Burhanuddin-Nahargarwala** [comment]
@biku1998, scenario is successfully created, actually Tools section was empty due to which, the scenario was not created.
