### ISSUE TITLE
Skills should be visible in the masterclass and project section also

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#13]
- If we created a masterclass or project, how we will get an idea of what skills are covered in a particular masterclass or project?

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/26d35996-9a21-496e-a38d-b9f3351bafbd)

**No skills are visible in this section**
 
- If we have an external scenario, then it can be identified that the given scenarios have these skills and which tool is required, but what if the scenario is created inside the masterclass? The skills of that scenario won't be visible. For that, we have to go to the masterclass, click on scenario edit, and check its skills.
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/568910ce-5547-447f-8698-3a09717605af)

(Note: VBA is created inside the MC)

- **Can't we show that skills in the Masterclass or Project, the way we show it in the external scenarios?**

**Comment by biku1998** [comment]
Put this in the creator channel as well. Will answer there. That's why I said questions there. Bugs here @Burhanuddin-Nahargarwala

**Comment by Burhanuddin-Nahargarwala** [comment]
Okay
