### ISSUE TITLE
The creators can change the slug, after creation of content - This shouldn't be allowed

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#21]
- The slug should be refreshed only once while creating of scenario, masterclass, or project.
- Afterwards, it should disable the option to refresh the slug.
- While editing, I refreshed the slug, and due to the new slug, the previous URL stopped working, as that slug is refreshed to the new one
https://www.stag-creator.enqurious.com/scenario/data-analysis-excel-xwcw  -- This is now throwing the error
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/29e411ca-120f-4d84-95e3-31941343c31f)

As after refreshed the slug changed, and the new URL is:
https://www.stag-creator.enqurious.com/scenario/data-analysis-excel-2

The responsibility lies with the creator to ensure care is taken, but it would also be beneficial for the platform to do so. Once the slug is generated for a content, it shouldn't change further to make the URL of that content static.

**Comment by biku1998** [comment]
Slug changes are allowed and a valid usecase. And yes if slug changes old url will not work, that's how it should behave.

**Comment by Burhanuddin-Nahargarwala** [comment]
Okay
