### ISSUE TITLE
Only numbers are accepted as tag name

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#24]
1. Open 'https://www.stag-creator.enqurious.com/' 
2. The user is already logged in.
3. Enter tag name with only numbers and select category.
4. Expected Result: Tag must not be created and throw an error message to the user.
5. Actual Result: Tag is created and added to the list of tags.

Screenshot: https://drive.google.com/file/d/1yY7N24JYPgwW2LQJiwDdr6Xyq5A3wpIR/view?usp=drive_link

**Comment by mskl-kashish** [comment]
Fixed the bug
Now at least one alphabet is required to create a tag.

**Comment by mskl-kashish** [comment]
@sheetalguptamahankali this issue has been fixed. Please verify and close it.

**Comment by sheetalguptamahankali** [comment]
The issue is fixed now
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/bec42150-a752-4e0b-aa2c-ef36d9a79ee1)
