### ISSUE TITLE
Grid mode and Hierarchy mode button names are not displayed in tag page.

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#25]
1. Open 'https://www.stag-creator.enqurious.com/' 
2. The user is already logged in.
3. Enter mandatory fields - Tag name and category. Also, enter parent tag.
4. After creation, go to check whether hierarchy is added correctly.
5. Expected Result: User is guided to the correct page to check whether it is added correctly or not.
6. Actual Result: User is confused as there are no names for grid/hierarchy mode icons.

Screenshot: https://drive.google.com/file/d/1ONNPdDoYQnbWCoOTIhBLinrV4de6Lpgq/view?usp=drive_link

**Comment by biku1998** [comment]
Hey @sheetalguptamahankali closing this ticket for now because we first need to observe whether others are facing issues or not. Team members are also trying the product and we haven't got anything from them.

**Comment by sheetalguptamahankali** [comment]
This is not a mandatory thing, anything is fine if everyone is able to use it
