### ISSUE TITLE
Cocreators popup is not showing close option

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#29]
Steps to reproduce:

1. Open 'https://www.stag-creator.enqurious.com/'
2. The user is already logged in.
3. Go to home page and select to add cocreators to a scenario that is in draft mode.
4. A pop up is shown where a user can add/edit/delete cocreators.
5. Expected Result: There is an option to close the popup user along with cancel, add buttons.
6. Actual Result: No option to close the pop up is provided.

Screenshot
![CloseOptionNotAvailableForCocreatorsPopup](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/84bc3e7e-423c-4459-9ff8-e63028fb8f80)

**Comment by mskl-kashish** [comment]
This issue is fixed. 
@sheetalguptamahankali please check and close it.

**Comment by sheetalguptamahankali** [comment]
I can see close (X) at top right now for the pop up.
So, closing this.

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/bb459864-c8d6-45e8-9666-e56ae1320046)
