### ISSUE TITLE
User creation-'Something went wrong' shows up when the 'accept link' is clicked second time.

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#3]
Steps to Reproduce:

1. Open Email invite
2. Click on 'Accept Invite'
3. A new browser window opens and user is asked to fill up a user creation form.
4. Close that window and go to the email and click 'Accept invite' again.
5. Expected Result: User is redirected to enqurious page and user form page shown
6. Actual Result: User is redirected to enqurious page but 'Something went wrong' error is thrown.

NOTE: The same error shows up in edge, chrome browser. Also, in incognito mode.

![SomethingWentWrongScreenshot](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/55a409aa-92ff-4e25-9afa-75313bcf8ec1)

**Comment by biku1998** [comment]
Expected resolve date - 12th March 2024

**Comment by biku1998** [comment]
@sheetalguptamahankali 
The user will now see an explicit error message saying the invite can only be clicked once and if they are visiting the second time, what steps they can take.

**Comment by sheetalguptamahankali** [comment]
The message that the invite can be clicked only once is shown in the email invite.

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/3160cd5b-39d4-4b54-8020-7c353ebe5bc2)
Closing this as it is fixed
