### ISSUE TITLE
Allows creation of scenario without selection of correct choice in choice inputs (Mcq/Checkbox)

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#33]
1. Create a scenario
2. Create a choice input (radio or checkbox)
3. Don't select the correct choice for the input
4. Create the scenario

- Expected Result: it should give the warning or error that select the correct choice for the inputs
- Actual result: The scenario is successfully created

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/65793182-c6f9-4069-a251-8a97daa0707a)

The given scenario is created with this input where no correct option is selected...

**Comment by biku1998** [comment]
Hey @Burhanuddin-Nahargarwala 
It's the same behavior as we have in the current version.  Doesn't qualify as a bug, but an enhancement that is planned but not a priority.
So closing this for now.

**Comment by Burhanuddin-Nahargarwala** [comment]
Okay bhai
