### ISSUE TITLE
The story video is not being reflected in the skill path.

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#35]
1. Go to the skills path section
2. Click on Create Path
3. Add the details of the skills path
4. Attach poster and story video
5. Click on Create.

**Expected Result:** The poster should be visible on the skill path, at the skill path section, and the story video should be there inside the skills path
**Actual Result:** Poster is visible, but The video is not visible

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/1c3bbd54-270c-4fee-bb38-2124bca01ccb)

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/bec64fa6-0d7b-409e-baf0-e61bbaa33c7b)

**Comment by mskl-kashish** [comment]
Hey @Burhanuddin-Nahargarwala  this is fixed now. Test again and close.

**Comment by Burhanuddin-Nahargarwala** [comment]
Thanks
