### ISSUE TITLE
Story video added during scenario/project creation is not reflected on scenario/project page.

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#37]
Steps:
1. Login/Launch https://www.stag-creator.enqurious.com/
2. Click + for scenario to create a scenario.
3. Add a story video too and save the scenario.
4. Open scenario and check both home/content page.
5. Expected Result: The story video is showing either on scenario main page or content page.
6. Actual Result: The story video is not showing on scenario main page or content page.

Unable to add video here due to size constraints but I can send on slack, if needed.
NOTE: A similar issue is raised for skill path, but this is not working for scenario/project too.

**Comment by mskl-kashish** [comment]
@sheetalguptamahankali This issue has been fixed , please test and close it.

**Comment by sheetalguptamahankali** [comment]
This is working fine now. Screenshot
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/87783580-4576-4494-b944-2d1893d3d590)
