### ISSUE TITLE
Non-admin creators are unable to add co-creators to the content

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#38]
1. Open 'https://www.stag-creator.enqurious.com/'
2. The non-admin creator is logged in.
3. Go to the home page and select to add cocreators to a scenario that is in draft mode.
4. A pop-up is shown where a user can add/edit/delete cocreators."
5. Try to add co-creator

**Expected Result**: A list of creators should be available, from where the user can select and add co-creator
**Actual Result**: Not showing the list of creators, instead the error pops up, have a look at the below video get more idea

https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/c1f8e665-5f2a-43c6-8ed6-abd98f5351ce

**Comment by Burhanuddin-Nahargarwala** [comment]
Also, the error is coming as `Request failed with status code 403`, it won't make the user understand what exactly this error conveys.

**Comment by biku1998** [comment]
Hey @Burhanuddin-Nahargarwala this is fixed now. Test again and close.

**Comment by Burhanuddin-Nahargarwala** [comment]
If there is no name of the creator, then only NA can be okay, why is there null also mentioned:
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/9cbd30c6-7862-48ff-8183-1e988ca40479)

**Comment by biku1998** [comment]
You are still seeing null? Can you refresh the browser once. If it's still there, don't close the issue.

**Comment by biku1998** [comment]
@Burhanuddin-Nahargarwala it's not showing NA when I tested, I think you didn't refresh the browser. Pls confirm and close this.

**Comment by Burhanuddin-Nahargarwala** [comment]
@biku1998, NA comes under creator, so it will be visible here, so I think this is a valid one. This is fixed...
