### ISSUE TITLE
User Creation-'Something went wrong' shows up even when user opens invite within 48 hours

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#4]
Steps to Reproduce:

1. Open Email invite between 24-48 hours after it was sent.
2. Click on 'Accept Invite'
3. Expected Result: User is redirected to enqurious page and user form page shown.
4. Actual Result: User is redirected to enqurious page but 'Something went wrong' error is thrown.

**Comment by biku1998** [comment]
Expected resolve date - 12th March 2024

**Comment by biku1998** [comment]
@sheetalguptamahankali Now since the expiry time is 24 hours, you will see an explicit error message informing you what went wrong and what steps they can take.

**Comment by sheetalguptamahankali** [comment]
By clicking on 'Accept invite' after 48 hours, the user is shown an error that the invite is not valid anymore.

Screenshot:
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/6c0376ba-14bd-4d02-8deb-b0a963f81bbd)

One more check to do between 24-48 hours and then will close this.

**Comment by sheetalguptamahankali** [comment]
I see the same error after 24 hours too. So, closing this issue.

![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/99d2303d-1b50-4ec7-9a49-0c9abacad68d)
