### ISSUE TITLE
No expiry date information provided in invite

### ISSUE THREAD

**Issue by sheetalguptamahankali** [enqurious/enqurious-platforms-bug-reporting#6]
Steps to Reproduce:
1. Open email invite.
2. Read content of the invite.
3. Expected Result: Expiry date for the invite to be provided in the email.
4. Actual Result: No expiry date details mentioned in the email.

**Comment by biku1998** [comment]
Expected resolve date - 12th March 2024

**Comment by biku1998** [comment]
Hey @sheetalguptamahankali This is fixed. You will now see a time to expire i.e. 24 hours in the invite email.

**Comment by sheetalguptamahankali** [comment]
Expiry details are mentioned in the email invite.
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/62695856/6f64053f-2b95-46b5-9e5a-6b8f4f6a6662)
So, closing it
