### ISSUE TITLE
Gives error when scenario is open at the first time

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#9]
When we create the scenario and open it first time, the following error occurs:
![image](https://github.com/enqurious/enqurious-platforms-bug-reporting/assets/105622461/3307f19d-9db6-4a3f-bc77-0b66895202b3)

We have to refresh the page, and then the page comes to edit the scenario

**Comment by biku1998** [comment]
@Burhanuddin-Nahargarwala can you test this once again? I've tried multiple times not able to reproduce.

**Comment by Burhanuddin-Nahargarwala** [comment]
Sure, will test it again

**Comment by Burhanuddin-Nahargarwala** [comment]
Ya @biku1998 , now it's not throwing the error.
